# see config.go "type Config" for more fields
clientid:
clientsecret:
bottoken:
adminuser:
http:
  # Use 0.0.0.0 in Docker so published ports can reach the bot.
  listen: "0.0.0.0:2202"
  public: "https://example.com"
backlog_limit: 200
errorlog: ""
statusmessage: "in the garbage"
slash_commands: true
